name: Delete Commit Records Weekly
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Delete commit records
      run: |
        git config --local user.email "20682299+tbbatbb@users.noreply.github.com"
        git config --local user.name "tbbatbb"
        git checkout --orphan new_branch
        git commit -m "init"
        git branch -D master
        git branch -m master
        git push -f origin master 